<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class ECBPreAspirantesSeeder_Parte1 extends Seeder{
public function run(): void{
DB::table('ECB_aspirantes')->insert([
            [
                'llamado_id'=>1,
                'compania_id'=>16,
                'nombre'=>'Wilfrido',
                'apellido'=>'Torres Delgado',
                'cedula'=>'2921698',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1978-03-12',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>53,
                'nombre'=>'JUAN WLADIMIR',
                'apellido'=>'ALFARO SILVA',
                'cedula'=>'3378721',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1991-05-27',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>42,
                'nombre'=>'Liz Rocio',
                'apellido'=>'Almada Aguero',
                'cedula'=>'3822423',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1983-11-27',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>63,
                'nombre'=>'Delsy Magali',
                'apellido'=>'González Cáceres',
                'cedula'=>'3866872',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1995-11-10',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>40,
                'nombre'=>'Hugo Javier',
                'apellido'=>'Paredes Rodríguez',
                'cedula'=>'3978087',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1995-02-10',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>5,
                'nombre'=>'Liz Maribel',
                'apellido'=>'Ferrer Pasotti',
                'cedula'=>'4027908',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1988-03-03',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>118,
                'nombre'=>'Diddier Dammian',
                'apellido'=>'Dominguez Gonzalez',
                'cedula'=>'4062876',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1995-01-07',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>83,
                'nombre'=>'Antonio',
                'apellido'=>'Villalba jara',
                'cedula'=>'4067786',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1981-03-21',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>78,
                'nombre'=>'María Natalia',
                'apellido'=>'Piris Paiva  ',
                'cedula'=>'4098774',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1990-11-07',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>4,
                'nombre'=>'Luis Enrique',
                'apellido'=>'Lopez Jara',
                'cedula'=>'4181653',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1992-04-01',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>40,
                'nombre'=>'Teresa De Jesús',
                'apellido'=>'Vera Verón',
                'cedula'=>'4320634',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1997-10-01',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>84,
                'nombre'=>'PABLINO',
                'apellido'=>'LUGO IBAÑEZ',
                'cedula'=>'4413164',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1984-06-22',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>9,
                'nombre'=>'Veronica Raquel',
                'apellido'=>'Rivarola Santacruz',
                'cedula'=>'4576977',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1998-09-28',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>130,
                'nombre'=>'DAISI GALILEA',
                'apellido'=>'SANTACRUZ BARRIE',
                'cedula'=>'4606460',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1999-11-26',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>26,
                'nombre'=>'CRIS STEFANI',
                'apellido'=>'GARCIA BRITEZ',
                'cedula'=>'4788819',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1995-06-28',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>84,
                'nombre'=>'CESIA KAREN',
                'apellido'=>'LAGRAÑA CLIVIO',
                'cedula'=>'4848657',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1987-04-20',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>2,
                'nombre'=>'Fabiola de Jesus',
                'apellido'=>'catalan Morel',
                'cedula'=>'4897095',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1987-09-17',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>79,
                'nombre'=>'Maria Eleuteria',
                'apellido'=>'Rodi Aguiletra',
                'cedula'=>'4898224',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1990-07-13',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>57,
                'nombre'=>'José Bladimir',
                'apellido'=>'Aranda Zorrilla',
                'cedula'=>'4971244',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1999-01-04',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>106,
                'nombre'=>'Victor',
                'apellido'=>'Benitez Cano',
                'cedula'=>'5012032',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1987-04-22',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>42,
                'nombre'=>'Andrea Leticia',
                'apellido'=>'Ortega Gomez',
                'cedula'=>'5046939',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1996-06-28',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>4,
                'nombre'=>'Pedro Luis',
                'apellido'=>'Quintana Mendoza',
                'cedula'=>'5129059',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-02-11',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>79,
                'nombre'=>'FERNANDO',
                'apellido'=>'MENDEZ ACOSTA',
                'cedula'=>'5182449',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1997-07-27',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>29,
                'nombre'=>'María Paz',
                'apellido'=>'Deniz Benitez',
                'cedula'=>'5228389',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-04-13',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>84,
                'nombre'=>'RODRIGO',
                'apellido'=>'GODOY SANABRIA',
                'cedula'=>'5230356',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-03-13',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>78,
                'nombre'=>'Hernan Rodrigo ',
                'apellido'=>'Martinez Piris ',
                'cedula'=>'5246154',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-07-18',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>16,
                'nombre'=>'Linzy Daihana',
                'apellido'=>'Roa Cañete',
                'cedula'=>'5296387',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1993-11-27',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>16,
                'nombre'=>'Federico Manuel',
                'apellido'=>'Galeno Ortiz',
                'cedula'=>'5396869',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1996-03-11',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>131,
                'nombre'=>'Diego',
                'apellido'=>'Rolon Cardozo',
                'cedula'=>'5425724',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1997-02-11',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>106,
                'nombre'=>'Deicy Gabriela',
                'apellido'=>'Estigarribia Gonzalez',
                'cedula'=>'5428906',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1998-11-20',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>20,
                'nombre'=>'Giovanni Mihail',
                'apellido'=>'Adorno del Puerto',
                'cedula'=>'5459046',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-07-06',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>48,
                'nombre'=>'Sofia Araceli',
                'apellido'=>'Aquino Ortega',
                'cedula'=>'5459893',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1998-05-15',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>63,
                'nombre'=>'Romina Araceli',
                'apellido'=>'Mindikoski Garcete',
                'cedula'=>'5469510',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1998-01-01',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>40,
                'nombre'=>'Katerin Beatriz',
                'apellido'=>'González Gutiérrez',
                'cedula'=>'5516947',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-05-24',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>23,
                'nombre'=>'Maria Fátima',
                'apellido'=>'Alegre Ruiz Díaz',
                'cedula'=>'5548690',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1998-09-16',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>83,
                'nombre'=>'Leandro Nicolás',
                'apellido'=>'Britez Cardozo',
                'cedula'=>'5615879',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2001-07-28',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>4,
                'nombre'=>'Hector Daniel',
                'apellido'=>'Sosa Medina',
                'cedula'=>'5626725',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1995-10-01',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>12,
                'nombre'=>' JUAN CARLOS',
                'apellido'=>'PERALTA ARRUA',
                'cedula'=>'5627782',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1994-04-27',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>12,
                'nombre'=>'DAMARIS ROXANA',
                'apellido'=>'BENITEZ PONCE',
                'cedula'=>'5634817',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-03-20',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>78,
                'nombre'=>'Juana Paola',
                'apellido'=>'Pintos Vera',
                'cedula'=>'5700644',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1994-06-26',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>97,
                'nombre'=>'FERNANDO JOSE',
                'apellido'=>'Morinigo',
                'cedula'=>'5748792',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2002-06-06',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>26,
                'nombre'=>'ARACELY ABIGAIL',
                'apellido'=>'GIMENEZ VALDEZ',
                'cedula'=>'5804591',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2000-05-10',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>16,
                'nombre'=>'Shirley Viviana',
                'apellido'=>'Quiñonez Chuchi',
                'cedula'=>'5806963',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1997-04-21',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>84,
                'nombre'=>'MILVA ADRIANA',
                'apellido'=>'CANO GIMENEZ',
                'cedula'=>'5831654',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2002-10-27',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>5,
                'nombre'=>'Osvaldo Rafael',
                'apellido'=>'Alfonso Bogado',
                'cedula'=>'5840051',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2005-08-19',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>83,
                'nombre'=>'Arnaldo Rodrigo',
                'apellido'=>'Rojas Martinez',
                'cedula'=>'5842568',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2000-12-20',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>35,
                'nombre'=>'Eresmilda',
                'apellido'=>'Ruiz Diaz Pelozo',
                'cedula'=>'5848072',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1995-01-20',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>5,
                'nombre'=>'Nayeli Thais',
                'apellido'=>'Esquivel Alfonso',
                'cedula'=>'5860937',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-07-10',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>5,
                'nombre'=>'Anahí María Cristina',
                'apellido'=>'Valdez Serrati',
                'cedula'=>'5906976',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-02-21',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>105,
                'nombre'=>'Braulio Ivan',
                'apellido'=>'Ojeda Alfonzo',
                'cedula'=>'5920779',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-12-24',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>45,
                'nombre'=>'Junior Ezequiel',
                'apellido'=>'Davalos Jimnez',
                'cedula'=>'5927050',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-08-22',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>79,
                'nombre'=>'YANINA',
                'apellido'=>'BUHRING GARCIA',
                'cedula'=>'5955540',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2001-03-17',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>29,
                'nombre'=>'María Angélica',
                'apellido'=>'Gonzalez Morel',
                'cedula'=>'5957904',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-06-01',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>11,
                'nombre'=>'Victor Benjamin',
                'apellido'=>'Onieva Medina',
                'cedula'=>'5966097',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-08-24',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>26,
                'nombre'=>'YANINA MARIA',
                'apellido'=>'BENITEZ COLNAGO',
                'cedula'=>'5991088',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-06-21',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>79,
                'nombre'=>'BRICE JOSIAS',
                'apellido'=>'GAUTO DIAZ',
                'cedula'=>'6033553',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-08-28',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>14,
                'nombre'=>'Mirna Beatriz',
                'apellido'=>'Vera Gamarra',
                'cedula'=>'6039209',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1996-04-10',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>106,
                'nombre'=>'Junior Sebastian',
                'apellido'=>'Bogado Haz ',
                'cedula'=>'6083956',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-02-24',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>84,
                'nombre'=>'MATIAS',
                'apellido'=>'AMARILLA BENITEZ',
                'cedula'=>'6085696',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-12-05',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>9,
                'nombre'=>'Carlos Isaias',
                'apellido'=>'Rodriguez Martinez',
                'cedula'=>'6087788',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-12-31',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>78,
                'nombre'=>' Karen Jazmin',
                'apellido'=>'Candia Benítez',
                'cedula'=>'6125692',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-06-09',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>40,
                'nombre'=>'Rita Ayelen',
                'apellido'=>'Sosa Moreno',
                'cedula'=>'6206204',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-07-01',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>4,
                'nombre'=>'Mirian',
                'apellido'=>'Pedrozo',
                'cedula'=>'6212774',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-11-30',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>106,
                'nombre'=>'Ninfa Beatriz',
                'apellido'=>'Yegros Arevalos',
                'cedula'=>'6215034',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1996-09-09',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>26,
                'nombre'=>'SONIA',
                'apellido'=>'PEÑA GARCETE',
                'cedula'=>'6272660',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1996-07-30',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>13,
                'nombre'=>'Luz Stefany',
                'apellido'=>'Barrios Villarreal',
                'cedula'=>'6284497',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1998-07-09',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>118,
                'nombre'=>'Hugo Emanuel',
                'apellido'=>'Fariña Villalba',
                'cedula'=>'6306043',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-10-30',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>12,
                'nombre'=>'JACKELINE JAEL',
                'apellido'=>'RAMIREZ SANTACRUZ',
                'cedula'=>'6318759',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-11-28',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>12,
                'nombre'=>' FRANCHESCA MONS',
                'apellido'=>'RECALDE RECALDE',
                'cedula'=>'6319476',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-01-12',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>45,
                'nombre'=>'Jose Esteban',
                'apellido'=>'Galeano Sanchez',
                'cedula'=>'6324967',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2001-03-17',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>50,
                'nombre'=>'Mathias Ivan',
                'apellido'=>'Miranda Lopez',
                'cedula'=>'6339002',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-09-23',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>56,
                'nombre'=>'Milagros Guadalupe',
                'apellido'=>'González Sanchez',
                'cedula'=>'6339310',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-01-26',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>78,
                'nombre'=>'Jaquelin Soledad',
                'apellido'=>'Leiva Avalos ',
                'cedula'=>'6345039',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1997-11-17',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>56,
                'nombre'=>'Shirley Aracely',
                'apellido'=>'Garcete Torres',
                'cedula'=>'6532452',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-05-21',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>12,
                'nombre'=>'MARIA LAURA',
                'apellido'=>'OVIEDO CHAVEZ ',
                'cedula'=>'6537622',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1997-04-24',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>26,
                'nombre'=>'SOLEDAD',
                'apellido'=>'TORRES MEZA',
                'cedula'=>'6548746',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-08-21',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>19,
                'nombre'=>'Marcos David',
                'apellido'=>'Perez Fretes',
                'cedula'=>'6551606',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1999-05-21',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>12,
                'nombre'=>'NAHIM SEBASTIAN',
                'apellido'=>'ORTEGA ALONSO',
                'cedula'=>'6558461',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-10-01',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>47,
                'nombre'=>'Juan Antonio',
                'apellido'=>'Zorrilla Paredes',
                'cedula'=>'6571246',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1998-08-07',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>77,
                'nombre'=>'SOFIA GISSELL',
                'apellido'=>'MANCUELLO RAMIREZ',
                'cedula'=>'6599537',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-03-10',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>97,
                'nombre'=>'Gricelda',
                'apellido'=>'Salinas Arrua',
                'cedula'=>'6602397',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-07-29',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>83,
                'nombre'=>'Angel David',
                'apellido'=>'Vera Rivas',
                'cedula'=>'6706269',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-10-22',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>52,
                'nombre'=>'JUANA CARIDAD',
                'apellido'=>'VAZQUEZ FERNANDEZ',
                'cedula'=>'6728604',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2001-06-24',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>95,
                'nombre'=>'Alver Ramón',
                'apellido'=>'Sanabria Cabral',
                'cedula'=>'6750643',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1995-05-17',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>30,
                'nombre'=>'Marco Antonio',
                'apellido'=>'Giménez Fariña',
                'cedula'=>'6761999',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2005-03-31',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>130,
                'nombre'=>'Luna Aracely',
                'apellido'=>'Sosa Coronel',
                'cedula'=>'6768274',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-12-11',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>11,
                'nombre'=>'Yago Naim',
                'apellido'=>'Vera Chirife',
                'cedula'=>'6796749',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-02-22',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>35,
                'nombre'=>'Patricia',
                'apellido'=>'Vargas Cañiza',
                'cedula'=>'6825946',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1995-03-17',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>77,
                'nombre'=>'ALEJANDRO',
                'apellido'=>'CANO CARDOZO ',
                'cedula'=>'6896851',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2002-02-19',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>84,
                'nombre'=>'MARCO ANTONIO',
                'apellido'=>'ALFONZO CENTURION',
                'cedula'=>'6900679',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-08-05',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>16,
                'nombre'=>'Rosalinda',
                'apellido'=>'Lezcano ovelar',
                'cedula'=>'6903239',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2000-01-13',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>79,
                'nombre'=>'ANA PABLA',
                'apellido'=>'GARCETE DA SILVA',
                'cedula'=>'6908835',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1997-10-20',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>33,
                'nombre'=>'Yesica Luján',
                'apellido'=>'Valiente Baez',
                'cedula'=>'6922686',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-10-18',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>42,
                'nombre'=>'Carmelo Agustin',
                'apellido'=>'Fouz Busto',
                'cedula'=>'6962586',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1999-07-16',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>28,
                'nombre'=>'Rodrigo Marciano',
                'apellido'=>'Cabaña',
                'cedula'=>'6987913',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1995-11-17',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>106,
                'nombre'=>'Cristhian Alcides',
                'apellido'=>'Ramirez Romero',
                'cedula'=>'7035625',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1999-03-27',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>26,
                'nombre'=>'FEDERICO',
                'apellido'=>'CUBAS ROLON',
                'cedula'=>'7038297',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2009-02-17',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>56,
                'nombre'=>'Jazmín Elizabeth',
                'apellido'=>'Ferreira Torales',
                'cedula'=>'7049273',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2005-10-05',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>102,
                'nombre'=>'Liz Yanina',
                'apellido'=>'Báez Cañiza',
                'cedula'=>'7139103',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-02-02',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>20,
                'nombre'=>'Evelin Mercedes',
                'apellido'=>'Fleitas Flores',
                'cedula'=>'7143055',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2001-09-24',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>53,
                'nombre'=>'YSMAEL',
                'apellido'=>'QUIÑONEZ BENITEZ',
                'cedula'=>'7156638',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1997-12-28',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>102,
                'nombre'=>'Hugo Gabriel',
                'apellido'=>'Fernández Merlo',
                'cedula'=>'7158472',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2002-08-02',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>77,
                'nombre'=>'JESUS GABRIEL',
                'apellido'=>'FERREIRA SAUCEDO',
                'cedula'=>'7191257',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2002-12-24',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>26,
                'nombre'=>'JOEL',
                'apellido'=>'BARRIOS GODOY',
                'cedula'=>'7197320',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2005-02-21',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>5,
                'nombre'=>'Mateo Giuliano',
                'apellido'=>'Rivero Manfredi',
                'cedula'=>'7236580',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-11-10',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>102,
                'nombre'=>'Cesar De Jesus',
                'apellido'=>'Martinez Roman',
                'cedula'=>'7337362',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-05-11',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>63,
                'nombre'=>'Kiara Janet',
                'apellido'=>' Duarte Vázquez',
                'cedula'=>'7431239',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-02-06',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>35,
                'nombre'=>'Fátima Elizabeth',
                'apellido'=>'Fernández Vera',
                'cedula'=>'7439395',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-05-08',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>33,
                'nombre'=>'Fernanda Lujan',
                'apellido'=>'Benítez Giménez',
                'cedula'=>'7446437',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-11-06',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>71,
                'nombre'=>'Nery Valerio',
                'apellido'=>'González Morinigo',
                'cedula'=>'7453239',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1999-11-04',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>50,
                'nombre'=>'Manuel Fabrizio',
                'apellido'=>'Benegas Noguera',
                'cedula'=>'7461966',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-10-20',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>102,
                'nombre'=>'Dimas Duban',
                'apellido'=>' Prieto Arevalos',
                'cedula'=>'7462527',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-08-06',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>19,
                'nombre'=>'Lujan Yeruti',
                'apellido'=>'Acosta Spelt',
                'cedula'=>'7491101',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2000-04-08',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>102,
                'nombre'=>'Nara Gabriela',
                'apellido'=>'Barrios Bonussi',
                'cedula'=>'7514627',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-01-20',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>16,
                'nombre'=>'Lucas',
                'apellido'=>'Achucarro Chávez',
                'cedula'=>'7531435',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-09-23',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>79,
                'nombre'=>'EVELYN MARICEL',
                'apellido'=>'CRUZ MARTINEZ',
                'cedula'=>'7534192',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-03-11',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>79,
                'nombre'=>'LIZ VERONICA',
                'apellido'=>'RAMIREZ CRUZ',
                'cedula'=>'7545281',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1997-06-28',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>47,
                'nombre'=>'Sandra',
                'apellido'=>'Martinez Velazquez',
                'cedula'=>'7567213',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2006-11-20',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>79,
                'nombre'=>'ADRIAN',
                'apellido'=>'SALINAS GIMENEZ',
                'cedula'=>'7570607',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-09-21',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>53,
                'nombre'=>'Daisy Romina',
                'apellido'=>'Cantero Servin',
                'cedula'=>'7742691',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-01-01',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>79,
                'nombre'=>'PERLA YANE',
                'apellido'=>'MARTINEZ BENITEZ',
                'cedula'=>'7768351',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2007-05-07',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>52,
                'nombre'=>'REBECA LARIZZA',
                'apellido'=>'TROCHE LOPEZ',
                'cedula'=>'7782892',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-03-25',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>45,
                'nombre'=>'Erwin Ariel',
                'apellido'=>'Aguayo Ruiz',
                'cedula'=>'7813435',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2003-04-01',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>29,
                'nombre'=>'Jeremías David',
                'apellido'=>'Mereles Ojeda',
                'cedula'=>'7916708',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-05-08',
                'sexo'=>'M',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>50,
                'nombre'=>'Maria del Carmen',
                'apellido'=>'Caceres Gonzalez',
                'cedula'=>'8000442',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2008-08-14',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>78,
                'nombre'=>'Leticia Lujan',
                'apellido'=>'León Leiva',
                'cedula'=>'8239116',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2004-04-16',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>78,
                'nombre'=>'Jessica Dahiana',
                'apellido'=>'Rossi Rojas ',
                'cedula'=>'8481357',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'2005-11-22',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'llamado_id'=>1,
                'compania_id'=>78,
                'nombre'=>'Rosario del Pilar',
                'apellido'=>'Fernández',
                'cedula'=>'40886576',
                'celular'=>null,
                'correo'=>null,
                'ciudad'=>null,
                'fecha_nacimiento'=>'1998-01-29',
                'sexo'=>'F',
                'estado'=>'PRE_ASPIRANTE',
                'observacion'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],

]);





}
}